using PrivateAiChat.Domain.Common;
using PrivateAiChat.Domain.Messages;

namespace PrivateAiChat.Domain.Conversations;

public sealed class Conversation : AuditableEntity
{
    private readonly List<Message> _messages = new();

    private Conversation()
    {
    }

    public Conversation(Guid userId, string? title = null) : this()
    {
        UserId = userId == Guid.Empty
            ? throw new ArgumentException("User id is required.", nameof(userId))
            : userId;

        Title = title?.Trim();
    }

    public Guid UserId { get; private set; }

    public string? Title { get; private set; }

    public IReadOnlyCollection<Message> Messages => _messages;

    public void RenameFromMessage(string content, int maxLength = 50)
    {
        if (string.IsNullOrWhiteSpace(content))
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(Title) && !IsAutoGeneratedTitle(Title))
        {
            return;
        }

        var normalizedContent = content.Trim().ReplaceLineEndings(" ");
        Title = normalizedContent.Length <= maxLength
            ? normalizedContent
            : normalizedContent[..maxLength].Trim();
    }

    private static bool IsAutoGeneratedTitle(string title) =>
        string.Equals(title, "New conversation", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(title, "Untitled conversation", StringComparison.OrdinalIgnoreCase);
}
