using PrivateAiChat.Domain.Common;
using PrivateAiChat.Domain.Messages;

namespace PrivateAiChat.Domain.Conversations;

public sealed class Conversation : AuditableEntity
{
    public const int MaxTitleLength = 200;

    private readonly List<Message> _messages = new();

    private Conversation()
    {
    }

    public Conversation(Guid userId, string? title = null) : this()
    {
        UserId = userId == Guid.Empty
            ? throw new ArgumentException("User id is required.", nameof(userId))
            : userId;

        Title = title?.Trim();
    }

    public Guid UserId { get; private set; }

    public string? Title { get; private set; }

    public IReadOnlyCollection<Message> Messages => _messages;

    public void Rename(string title)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            throw new ArgumentException("Conversation title is required.", nameof(title));
        }

        var trimmedTitle = title.Trim();
        if (trimmedTitle.Length > MaxTitleLength)
        {
            throw new ArgumentException($"Conversation title must be {MaxTitleLength} characters or fewer.", nameof(title));
        }

        Title = trimmedTitle;
    }

    public void RenameFromMessage(string content, int maxWords = 8, int maxLength = 50)
    {
        if (string.IsNullOrWhiteSpace(content))
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(Title) && !IsAutoGeneratedTitle(Title))
        {
            return;
        }

        var words = content
            .Trim()
            .ReplaceLineEndings(" ")
            .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Take(maxWords);

        var title = string.Join(' ', words);
        Title = title.Length <= maxLength
            ? title
            : title[..maxLength].Trim();
    }

    private static bool IsAutoGeneratedTitle(string title) =>
        string.Equals(title, "New conversation", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(title, "Untitled conversation", StringComparison.OrdinalIgnoreCase);
}
